import { db } from "../app.js"
// import ErrorHandler from "../middleware/customError.js"

export async function roomSchema() {

    const roomTable = `CREATE TABLE IF NOT EXISTS ROOMS (
      ROOM_ID VARCHAR(200) PRIMARY KEY,
    ADMIN_REF_ID VARCHAR(200) NOT NULL,
    PRICE INT NOT NULL,
    LOCALITY VARCHAR(40) NOT NULL,
    DISTRICT VARCHAR(25) NOT NULL,
    LATITUDE DECIMAL(10, 8) DEFAULT NULL,
    LONGITUDE DECIMAL(11, 8) DEFAULT NULL,
    RATING DECIMAL(3,2) DEFAULT 0.00 CHECK (RATING BETWEEN 0.00 AND 5.00),
    RATING_COUNT_USER INT DEFAULT 0,
    AVAILABILITYDATE DATE NOT NULL,
    ROOM_TYPE ENUM('PRIVATE', 'SHARED', 'FAMILY') NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'UNISEX') NOT NULL,
    BED_SIT ENUM('YES', 'NO') NOT NULL,
    AC ENUM('YES', 'NO') NOT NULL,
    TOILET ENUM('YES', 'NO') NOT NULL,
    BATHROOM ENUM('YES', 'NO') NOT NULL,
    FAN ENUM('YES', 'NO') NOT NULL,
    KITCHEN ENUM('YES', 'NO') NOT NULL,
    TABLE_CHAIR ENUM('YES', 'NO') NOT NULL,
    ALMIRA ENUM('YES', 'NO') NOT NULL,
    WATER_SUPPLY INT NOT NULL CHECK (WATER_SUPPLY BETWEEN 1 AND 24),
    WATER_DRINK ENUM('NAL', 'FILTERED') NOT NULL,
    PARKING_SPACE ENUM('Yes', 'No') NOT NULL,
    WIFI ENUM('YES', 'NO') NOT NULL,
    ELECTRICITY_BILL ENUM('YES', 'NO') NOT NULL,
    DISCRIPTION VARCHAR(500) NOT NULL,
    RULES VARCHAR(255) NOT NULL,
    PHOTO_URL_ID VARCHAR(200) NOT NULL,
    CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ADMIN_REF_ID) REFERENCES ADMINS(ADMIN_ID) ON DELETE CASCADE,

    FULLTEXT INDEX idx_location (LOCALITY, DISTRICT),
    INDEX  idx_filters (PRICE,DISTRICT, AVAILABILITYDATE, ROOM_TYPE, GENDER)
);`

    const connection = await db.getConnection()
    try {
        await connection.query(roomTable)
        connection.release()
        console.log("room table created");

    } catch (error) {
        connection.release()
        console.log("room table not created");
    }
}



